name: Commit test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: scalar-labs/scalar-licensing
          token: ${{ secrets.GH_PAT }}

      - name: Setup and execute Gradle 'installDist' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist

      - name: generate a timestamp
        run: |
          echo "${{ secrets.PRIVATE_KEY_PEM }}" > $HOME/private-key.pem
          lib/build/install/lib/bin/generate-signed-timestamp --private-key-file=$HOME/private-key.pem > $HOME/timestamp
          
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      
      - run: |
          cp $HOME/timestamp .
          git config user.name github-actions
          git config user.email action@github.com
          git add .
          git commit --amend -m "generated"
          git push -f
